Models/Landmark.cs
using Microsoft.AspNetCore.Authorization;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace FinalCapstone.Models
{
    public class Landmark : Neighborhood
    {
        [Required(ErrorMessage = "Please enter the code.")]
        [StringLength(4, ErrorMessage = "Code cannot be more or less than 4 characters", MinimumLength = 4)]
        [Display(Name = "Attraction Code:")]
        public string Code { get; set; }

        [Required(ErrorMessage = "Please enter a name.")]
        [Display(Name = "Attraction Name:")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Please enter a type.")]
        [RegularExpression(@"(Restaurant|Park|Arena|Activity Center)", ErrorMessage = "Code must be Restaurant, Park, Arena, or Activity Center")]
        [Display(Name = "Attraction Type:")]
        public string Type { get; set; }

        [Required(ErrorMessage = "Please enter a description.")]
        [StringLength(800, ErrorMessage = "Description cannot be more than 800 characters")]
        [Display(Name = "Attraction Description:")]
        public string Description { get; set; }

        [Required(ErrorMessage = "Please enter the hours.")]
        [Display(Name = "Attraction Hours:")]
        public string Hours { get; set; }

        [Required(ErrorMessage = "Please enter feature(s).")]
        [Display(Name = "Attraction Features:")]

        public string Features { get; set; }

        public string AttractionNeighborhoodCode { get; set; }
        public decimal Latitude { get; set; }
        public decimal Longitude { get; set; }
    }
}

Controllers/LandmarkController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using FinalCapstone.Dal;
using FinalCapstone.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Web;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;
using FinalCapstone.Dal.IDAL;

namespace FinalCapstone.Controllers
{
    [AllowAnonymous]
    public class LandmarkController : Controller
    {
        private readonly ILandmarkDAL _landmarkDAL;
        private readonly IReviewDAL _reviewDAL;
        private readonly IVoteDAL _voteDAL;

        public LandmarkController(ILandmarkDAL landmarkDAL, IReviewDAL reviewDAL, IVoteDAL voteDAL)
        {
            _landmarkDAL = landmarkDAL;
            _reviewDAL = reviewDAL;
            _voteDAL = voteDAL;
        }

        public IActionResult Index(string id)
        {
            IList<Landmark> neighboodLandmarks = _landmarkDAL.GetNeighborhoodLandmarks(id);

            return View(neighboodLandmarks);
        }

        public IActionResult Detail(string id, DisplayReviewsViewModel model)
        {

            IList<Landmark> landMarkDetail = _landmarkDAL.GetLandmark(id);
            IList<Review> reviews = _reviewDAL.GetAllReviews(id);

            model.Landmarks = landMarkDetail;
            model.Reviews = reviews;

            var abs = Path.GetFullPath("~/wwwroot/userImages/").Replace("~\\", "");

            model.Images = Directory.EnumerateFiles(abs)
                                .Select(fn => Path.GetFileName(fn));

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Vote(Vote model, string id)
        {
            var vote = model.Value;
            model.Username = HttpContext.User.Identity.Name;
            model.AttractionCode = id;
            _voteDAL.SaveVote(model);

            return RedirectToAction("Neighborhoods", "Neighborhood");
        }

        public IActionResult Delete (string id)
        {
            _landmarkDAL.DeleteLandmark(id);
            return RedirectToAction("Neighborhoods", "Neighborhood");
        }

    }
}

Controllers/ReviewController.cs
using System;
using FinalCapstone.Dal;
using FinalCapstone.Dal.IDAL;
using FinalCapstone.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace FinalCapstone.Controllers
{
    public class ReviewController : Controller
    {
        private readonly IReviewDAL _reviewDAL;
        private readonly ILandmarkDAL _landmarkDAL;
        private const string NewReviewResultKey = nameof(NewReviewResultKey);

        public ReviewController(IReviewDAL reviewDAL, ILandmarkDAL landmarkDAL)
        {
            _reviewDAL = reviewDAL;
            _landmarkDAL = landmarkDAL;
        }

        [HttpGet]
        public IActionResult NewReview(string id)
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult NewReview(Review model, string id)
        {
            model.ReviewDate = DateTime.UtcNow;
            model.Username = HttpContext.User.Identity.Name;
            model.AttractionCode = id;

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            _reviewDAL.SaveNewReview(model);

            TempData[NewReviewResultKey] = $"Thanks for sharing your experience, {model.Username}! Have an AMAZING day!";

            return RedirectToAction("Neighborhoods","Neighborhood");
        }
    }
}

Controllers/UploadController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using FinalCapstone.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Hosting.Server;
using Microsoft.AspNetCore.Mvc;

namespace FinalCapstone.Controllers
{
    public class UploadController : Controller
    {
        private readonly IHostingEnvironment _environment;

        // Constructor
        public UploadController(IHostingEnvironment IHostingEnvironment)
        {
            _environment = IHostingEnvironment;
        }


        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(string name, string id)
        {
            var newFileName = string.Empty;

            if (HttpContext.Request.Form.Files != null)
            {
                var fileName = string.Empty;
                string PathDB = string.Empty;

                var files = HttpContext.Request.Form.Files;

                foreach (var file in files)
                {
                    if (file.Length > 0)
                    {
                        //Getting FileName
                        fileName = ContentDispositionHeaderValue.Parse(file.ContentDisposition).FileName.Trim('"');

                        //Assigning Unique Filename (Guid)
                        var myUniqueFileName = Convert.ToString(Guid.NewGuid());

                        //Getting file Extension
                        var FileExtension = Path.GetExtension(fileName);

                        // concating  FileName + FileExtension
                        newFileName = myUniqueFileName + FileExtension;

                        // Combines two strings into a path.
                        fileName = Path.Combine(_environment.WebRootPath, "userImages") + $@"\{id}-{newFileName}";

                        // if you want to store path of folder in database
                        PathDB = "userImages/" + newFileName;

                        using (FileStream fs = System.IO.File.Create(fileName))
                        {
                            file.CopyTo(fs);
                            fs.Flush();
                        }
                    }
                }

                
            }
            //return RedirectToAction("Neighborhoods","Neighborhood");
            return RedirectToAction("userImages","Home");
        }


        public ActionResult UserImages()
        {
            var model = new UploadImage()
            {
                Images = Directory.EnumerateFiles(Path.Combine(_environment.WebRootPath, "~/userImages"))
                                  .Select(fn => "~/userImages" + Path.GetFileName(fn))
            };
            return View(model);
        }
    }
}

Views/Landmark/Detail.cshtml
@model DisplayReviewsViewModel
@{
    ViewData["Title"] = "Detail";
}

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css">

<style>

    h2, h3, p, div {
        text-align: center;
    }
</style>

<body>
    @foreach (Landmark landmark in Model.Landmarks)
    {
        <h2><b>@(landmark.Name)</b></h2>
        <p id="landmark-italics">@(landmark.NeighborhoodName)</p>
        <section>
            <div>
                <img class="image-detail" src="~/images/@(landmark.NeighborhoodId)-@(landmark.Code).jpg" alt="@landmark.Name">
            </div>
            <div>
                <h5>@landmark.Type</h5>
                <h5>@landmark.AttractionAddress</h5>
                <h5>Hours: @landmark.Hours</h5>
                <h5>@landmark.Description</h5>
                <h5>Features: @landmark.Features</h5>
                @if (landmark.Features.Contains("alcohol"))
                {
                    <i class="fas fa-wine-glass-alt"></i>
                }
                @if (landmark.Features.Contains("cafe"))
                {
                    <i class="fas fa-coffee"></i>
                }
                @if (landmark.Features.Contains("friendly"))
                {
                    <i class="fas fa-child"></i>
                }
            </div>
            <div>
                <form asp-action="AddToItinerary" asp-controller="Itinerary" asp-route-id="@(landmark.Code)" method="post">
                    <input type="hidden" asp-for="@(landmark.Code)" />
                    <div>
                        <button id="grey-button" type="submit">Add to Itinerary</button>
                    </div>
                </form>
            </div>
            @if (User.Identity.IsAuthenticated)
            {
                <div>
                    <form asp-action="NewReview" asp-controller="Review" asp-route-id="@(landmark.Code)" method="get">
                        <input type="hidden" asp-for="@(landmark.Code)" />
                        <div>
                            <button id="grey-button" type="submit">Add a Review</button>
                        </div>
                    </form>
                </div>
                @if (User.Identity.Name.Contains("admin"))
                {
                    <div>
                        <form asp-action="Delete" asp-controller="Landmark" asp-route-id="@(landmark.Code)" method="post">
                            <input type="hidden" asp-for="@(landmark.Code)" />
                            <div>
                                <button id="grey-button" type="submit">Delete Landmark</button>
                            </div>
                        </form>
                    </div>
                }
            }
        </section>
    }

</body>


<section class="container">
    <div>
        <div class="row">
            <div class="col-sm-6">
                <div id="my-slider" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner" role="listbox">
                        @foreach (Landmark landmark in Model.Landmarks)
                        {
                            <div class="item active">
                                <img class="image-detail" src="~/images/@(landmark.NeighborhoodId)-@(landmark.Code).jpg" alt="@landmark.Name">
                            </div>
                        }
                        @foreach (Landmark landmark in Model.Landmarks)
                        {
                            @foreach (var image in Model.Images)
                            {
                                if (image.Contains(landmark.Code))
                                {
                                    <div class="item">
                                        <img src="~/userImages/@(image)" class="img-responsive center-block" alt="@landmark.Name Photo">
                                    </div>
                                }
                            }
                        }
                    </div>
                    <a class="left carousel-control" href="#my-slider" role="button" data-slide="prev">
                        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                    </a>
                    <a class="right carousel-control" href="#my-slider" role="button" data-slide="next">
                        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="container">
    @if (User.Identity.IsAuthenticated)
    {
        @foreach (Landmark landmark in Model.Landmarks)
        {
            <form method="post" enctype="multipart/form-data" asp-controller="Upload" asp-action="Index" asp-route-id="@(landmark.Code)">
                <div class="form-group">
                    <div class="col-md-10">
                        <p>Upload one or more files using this form:</p>
                        <input type="file" name="files" multiple />
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-10">
                        <input type="submit" value="Upload" />
                    </div>
                </div>
            </form>
        }
    }
</section>

@foreach (Landmark landmark in Model.Landmarks)
{
    <h3><b>@(landmark.Name) Reviews</b></h3>
}

<section class="container">
    <table class="table-striped">
        <div class="row">
            @foreach (Review review in Model.Reviews)
            {
                <tr>
                    <td><strong>@review.Subject</strong></td>
                </tr>
                <tr>
                    <td>
                        @for (int i = 0; i < @review.Rating; i++)
                        {
                            <img class="ratings" src="~/images/Buckeye.png" />;
                        }
                    </td>
                </tr>
                <tr style="font-size: 75%;">
                    <td>by @review.Username</td>
                </tr>
                <tr style="font-size: 75%;">
                    <td>on @review.ReviewDate</td>
                </tr>
                <tr style="font-size: 75%;">
                    <td>@review.Message</td>
                </tr>
            }
        </div>
    </table>
</section>


Views/Landmark/Index.cshtml
@model IList<Landmark>
@{
    ViewData["Title"] = "NeighborhoodView";
}



<section id="landmarks" class="wrapper special">
    <div class="flex-container">
        @foreach (Landmark landmark in Model)
        {
            <div id="box">
                <h3><b>@landmark.Name</b></h3>
                <h4>@landmark.AttractionAddress</h4>
                <a asp-controller="Landmark" asp-action="Detail" asp-route-id="@(landmark.Code)">
                    <img class="neighborhood-image" src="~/images/@(landmark.NeighborhoodId)-@(landmark.Code).jpg" alt="@landmark.NeighborhoodName Photo">
                </a>
                <form asp-controller="Landmark" asp-action="Detail" asp-route-id="@(landmark.Code)">
                    <button id="grey-button" type="submit">More</button>
                </form>
            </div>
        }
    </div>
</section>